#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username $POSTGRES_USER --dbname $POSTGRES_DB <<-EOSQL
        CREATE USER $PONG_DB_USER WITH PASSWORD '$PONG_DB_PASSWORD';
        GRANT CREATE ON DATABASE $POSTGRES_DB TO $PONG_DB_USER;
        CREATE SCHEMA AUTHORIZATION $PONG_DB_USER;
EOSQL
